### ISSUE TITLE
Implement config loading

### ISSUE THREAD

**Issue by boarnoah** [Brightspace/bmx#201]
Extensions.Configuration.Ini should work.

Config as defined in bmx v2.0:

```
type UserConfig struct {
	AllowProjectConfigs bool
	Org                 string
	User                string
	Account             string
	Role                string
	Profile             string
}
```

Read from ~/.bmx/config file and optionally .bmx files inside CWD (read recursively, could be in sub-folders).

**Comment by cfbao** [comment]
The current behaviour also reads up the directory chain, e.g. `/project/.bmx` will be read if my CWD is `/project/a/b/c` and there's no other `.bmx` in between.

**Comment by boarnoah** [comment]
Gotta say, that behavior is a bit weird. I've generally seen apps that read recursively down the tree for config files but not up the tree 😆

**Comment by cfbao** [comment]
> Gotta say, that behavior is a bit weird. I've generally seen apps that read recursively down the tree for config files but not up the tree 😆

I feel it's a pretty common pattern.
Git commands work in subfolders of a repo because it looks for .git up the chain. [Editorconfig](https://editorconfig.org/#file-location) and [nuget.config](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#config-file-locations-and-uses) are also searched up the chain, to name a few.
