### ISSUE TITLE
Support output format expected by aws credentials_process

### ISSUE THREAD

**Issue by dougmoscrop** [Brightspace/bmx#204]
Something like:

> bmx login

Would prompt you for:

- Org (default read from bmx confing)
- Username (default read from bmx config)
- Password

And just setup/refresh the Okta session.

Then in `~/.aws/credentials`:

```ini
[dev-my-account]
credential_process = bmx aws-credentials --account=Dev-MyAccount --role=Dev-MyAccount-Owner
```

No opinion on the actual command, could also be `bmx print --aws` or `bmx print --json` and so on.

I think this has the same "failure mode" as when the `bmx write` credentials are expired (credentials process would just return the expired credentials if it can't renew them) but it avoids having to type in profile, account and role names as often.

**Comment by boarnoah** [comment]
Implemented via: #443

The workflow is:

Setup credential process with a role (once):
     ``bmx write --use-credential-process --account Dev-MyAccount --role Dev-MyAccount-Owner --profile dev-my-account``
 
Then in the future you need to do ``bmx login`` in order to refresh Okta credentials.

There is caching for the generated AWS credentials #384 
- With ``--duration`` set for > 20 mins (default is 60), credentials will be refreshed when < 15 mins to expiry
- With shorter duration than that it operates on a sliding window, at a minimum when < 10 mins to expiry
